const INTERNET_MOMENTS = [
  { ref: "man vs bear viral tiktok", hint: "she chose the bear" },
  { ref: "the dress — blue/black or white/gold", hint: "nobody agrees on what they saw" },
  { ref: "salt bae", hint: "someone sprinkles something with unnecessary precision" },
  { ref: "we did it reddit", hint: "the crowd takes credit for something they didn't do" },
  { ref: "girl dinner", hint: "this is her meal. it is not enough. it is everything." },
  { ref: "NPC livestreamer", hint: "she moves like she is running a loop" },
  { ref: "very demure very mindful", hint: "she is being very demure about this" },
  { ref: "brain rot", hint: "something here has fully rotted" },
  { ref: "understood the assignment", hint: "she understood the assignment" },
  { ref: "we are so back / it is so over", hint: "pick one. make it count." },
  { ref: "main character syndrome", hint: "everyone else is just an NPC" },
{ ref: "this is fine dog", hint: "everything is visibly on fire" },
{ ref: "distracted boyfriend", hint: "he has noticed something else" },
{ ref: "woman yelling at cat", hint: "one side is emotional, the other is eating salad" },
{ ref: "gigachad", hint: "the impossibly correct specimen" },
{ ref: "sigma male", hint: "he has rejected society and purchased a podcast microphone" },
{ ref: "skibidi toilet", hint: "nobody can explain why this became civilization" },
{ ref: "ohio meme", hint: "only in ohio" },
{ ref: "rizz", hint: "he possesses inexplicable charisma" },
{ ref: "the backrooms", hint: "you have clipped out of reality" },
{ ref: "liminal spaces", hint: "this place feels wrong for some reason" },
{ ref: "analog horror", hint: "the VHS tape knows something" },
{ ref: "NPC meme", hint: "their dialogue tree has ended" },
{ ref: "touch grass", hint: "please go outside immediately" },
{ ref: "chronically online", hint: "they have seen too much internet" },
{ ref: "ratio", hint: "the replies have spoken" },
{ ref: "cope", hint: "that explanation sounds self-soothing" },
{ ref: "seethe", hint: "they are not taking this well" },
{ ref: "based", hint: "unexpectedly respectable" },
{ ref: "cringe", hint: "secondhand embarrassment detected" },
{ ref: "mid", hint: "it exists. that is all." },
{ ref: "let him cook", hint: "the vision is not yet complete" },
{ ref: "cooked", hint: "the situation cannot be salvaged" },
{ ref: "delulu", hint: "delusion has become strategy" },
{ ref: "girl math", hint: "the arithmetic is emotionally correct" },
{ ref: "boy math", hint: "the arithmetic is emotionally incorrect" },
{ ref: "girlboss", hint: "she is succeeding, perhaps too hard" },
{ ref: "gatekeep gaslight girlboss", hint: "the holy trinity" },
{ ref: "beige flag", hint: "a strangely specific personality trait" },
{ ref: "red flag", hint: "abandon ship" },
{ ref: "green flag", hint: "unexpectedly healthy behavior" },
{ ref: "ick", hint: "attraction has been instantly deleted" },
{ ref: "situationship", hint: "nobody involved can define the relationship" },
{ ref: "soft launching", hint: "someone is hiding a partner in frame" },
{ ref: "hard launching", hint: "the relationship is now public information" },
{ ref: "quiet quitting", hint: "doing exactly what the job requires" },
{ ref: "lying flat", hint: "opting out of the hustle" },
{ ref: "antiwork", hint: "the spreadsheet can wait" },
{ ref: "rent free", hint: "it occupies too much mental space" },
{ ref: "doomscrolling", hint: "one more terrible post" },
{ ref: "doomposting", hint: "the future has been cancelled" },
{ ref: "weird twitter", hint: "the joke has escaped conventional structure" },
{ ref: "shitposting", hint: "quality was never the objective" },
{ ref: "posting through it", hint: "the emotional crisis continues online" },
{ ref: "many such cases", hint: "apparently this keeps happening" },
{ ref: "source: i made it up", hint: "citation unavailable" },
{ ref: "bro visited his friend", hint: "something catastrophic has happened" },
{ ref: "nah id win", hint: "confidence exceeding available evidence" },
{ ref: "stand proud", hint: "you were strong" },
{ ref: "is he stupid?", hint: "the internet's preferred question" },
{ ref: "they don't know", hint: "the secret remains mine alone" },
{ ref: "nobody: absolutely nobody:", hint: "someone did something unprompted" },
{ ref: "how do you do fellow kids", hint: "an institution attempts relevance" },
{ ref: "cheems", hint: "speech impediment dog wisdom" },
{ ref: "doge", hint: "such internet. very meme." },
{ ref: "stonks", hint: "financial expertise not required" },
{ ref: "diamond hands", hint: "selling is not an option" },
{ ref: "to the moon", hint: "investment strategy powered by optimism" },
{ ref: "ape together strong", hint: "collective irrationality" },
{ ref: "goblin mode", hint: "personal standards have been suspended" },
{ ref: "feral", hint: "civilization is losing its grip" },
{ ref: "no thoughts head empty", hint: "the brain is offline" },
{ ref: "he just like me fr", hint: "uncomfortable personal identification" },
{ ref: "the masculine urge", hint: "an extremely specific impulse" },
{ ref: "the feminine urge", hint: "an equally specific impulse" },
{ ref: "corecore", hint: "an emotional montage of the human condition" },
{ ref: "cottagecore", hint: "internet yearning for rural fantasy" },
{ ref: "goblincore", hint: "crow brain aesthetics" },
{ ref: "AI generated hands", hint: "something is wrong with the fingers" },
{ ref: "prompt engineer", hint: "typing has become a profession" },
{ ref: "chatgpt wrote this", hint: "suspiciously polished prose" },
{ ref: "dead internet theory", hint: "what if everyone here is a bot" },
{ ref: "reply guy", hint: "he appears beneath every post" },
{ ref: "cancelled", hint: "today's public execution" },
{ ref: "receipts", hint: "the screenshots have arrived" },
{ ref: "subtweet", hint: "a targeted message without naming names" },
{ ref: "parasocial relationship", hint: "they feel like close friends who have never met" },
{ ref: "babe wake up", hint: "a new development has dropped" },
{ ref: "the algorithm", hint: "an invisible force controls all outcomes" },
{ ref: "for you page", hint: "the machine knows your interests" },
{ ref: "i'm looking for the guy", hint: "an impossible search begins" },
{ ref: "absolute cinema", hint: "peak culture has been achieved" },
{ ref: "go piss girl", hint: "a strange form of encouragement" },
{ ref: "woman in STEM", hint: "she is engineering a terrible decision" },
{ ref: "unhinged", hint: "restraints have been removed" },
{ ref: "canon event", hint: "this suffering is mandatory" },
{ ref: "he's literally me", hint: "dangerous levels of identification" },
{ ref: "POV", hint: "that is not how POV works anymore" },
{ ref: "normalize this", hint: "social consensus is being requested" },
{ ref: "you won the internet today", hint: "temporary online supremacy achieved" },
{ ref: "the internet remains undefeated", hint: "collective creativity has become dangerous" },
{ ref: "birds aren't real", hint: "the pigeons are government surveillance devices" },
{ ref: "dead internet theory", hint: "most of the internet is bots talking to bots" },
{ ref: "gang stalking", hint: "they believe strangers are coordinating against them" },
{ ref: "mk ultra", hint: "the CIA definitely did something weird here" },
{ ref: "project blue beam", hint: "the fake alien invasion is coming any day now" },
{ ref: "chemtrails", hint: "those airplane lines are supposedly not just clouds" },
{ ref: "lizard people", hint: "the world's leaders may be reptiles" },
{ ref: "new world order", hint: "a secret global elite controls everything" },
{ ref: "illuminati", hint: "the triangle appears again" },
{ ref: "bohemian grove", hint: "powerful people meet in the woods for mysterious reasons" },
{ ref: "bilderberg group", hint: "another meeting nobody is supposed to understand" },
{ ref: "reptilian shapeshifters", hint: "their eyes glitched for a frame" },
{ ref: "moon landing hoax", hint: "they think it was filmed on a soundstage" },
{ ref: "flat earth", hint: "the horizon has become a personality trait" },
{ ref: "hollow earth", hint: "there is apparently another world underneath us" },
{ ref: "antarctica conspiracy", hint: "something important is hidden beyond the ice" },
{ ref: "simulation theory", hint: "reality may be running on somebody else's hardware" },
{ ref: "mandela effect", hint: "everyone remembers it differently" },
{ ref: "berenstain bears", hint: "the spelling has allegedly changed timelines" },
{ ref: "cern opened a portal", hint: "physics has gone too far" },
{ ref: "quantum immortality", hint: "you never experience your own death" },
{ ref: "targeted individual", hint: "they believe the universe is watching them specifically" },
{ ref: "crisis actor", hint: "every event is supposedly staged" },
{ ref: "false flag operation", hint: "nothing is ever what it appears to be" },
{ ref: "pizzagate", hint: "the basement that didn't exist" },
{ ref: "qanon", hint: "the clues are hidden in cryptic posts" },
{ ref: "the storm is coming", hint: "the promised reckoning never arrives" },
{ ref: "adrenochrome", hint: "internet mythology disguised as research" },
{ ref: "wayfair conspiracy", hint: "the furniture is suspiciously expensive" },
{ ref: "5g mind control", hint: "the cell tower is apparently responsible" },
{ ref: "vaccines contain microchips", hint: "the tracking device is somehow microscopic" },
{ ref: "black helicopters", hint: "unmarked aircraft mean something ominous" },
{ ref: "number stations", hint: "the radio keeps reading random numbers" },
{ ref: "HAARP", hint: "the weather is being controlled remotely" },
{ ref: "area 51", hint: "the aliens are probably in there" },
{ ref: "men in black", hint: "someone wants witnesses to stop talking" },
{ ref: "roswell incident", hint: "the weather balloon explanation remains controversial" },
{ ref: "ufo cover-up", hint: "the government has known all along" },
{ ref: "ancient aliens", hint: "humans definitely couldn't have built that" },
{ ref: "lost civilization of atlantis", hint: "there was supposedly an advanced society before history" },
{ ref: "giants existed", hint: "the skeleton photo was removed from the internet" },
{ ref: "mud flood theory", hint: "an entire civilization was buried recently" },
{ ref: "tartaria", hint: "the missing empire behind every old building" },
{ ref: "black knight satellite", hint: "something ancient is orbiting earth" },
{ ref: "face on mars", hint: "the blurry photo changes everything" },
{ ref: "paul is dead", hint: "the beatle was secretly replaced" },
{ ref: "elvis is alive", hint: "someone saw him at a grocery store" },
{ ref: "tu pac is alive", hint: "he is reportedly living somewhere unexpected" },
{ ref: "avril lavigne replacement theory", hint: "they think the original singer disappeared" },
{ ref: "clone theory", hint: "that celebrity has been replaced" },
{ ref: "celebrity humiliation ritual", hint: "the performance was supposedly symbolic" },
{ ref: "predictive programming", hint: "movies are secretly telling the future" },
{ ref: "the matrix glitch", hint: "reality briefly revealed the seams" },
{ ref: "npc theory", hint: "some people are allegedly background characters" },
{ ref: "backrooms found footage", hint: "someone accidentally escaped reality" },
{ ref: "slenderman sightings", hint: "the tall figure keeps appearing in photos" },
{ ref: "cicada 3301", hint: "an impossibly elaborate puzzle is recruiting people" },
{ ref: "polybius", hint: "the arcade machine nobody can prove existed" },
{ ref: "lake city quiet pills", hint: "a reddit mystery nobody fully solved" },
{ ref: "maxwellhill account theory", hint: "an old reddit account became unexpectedly interesting" },
{ ref: "celebrities are secretly immortal", hint: "they have looked the same for decades" },
{ ref: "time traveler john titor", hint: "a forum poster claimed to be from the future" },
{ ref: "finland does not exist", hint: "the country is allegedly a fishing conspiracy" },
{ ref: "wyoming does not exist", hint: "have you actually met anyone from there" },
{ ref: "birds work for the bourgeoisie", hint: "the joke conspiracy has evolved" },
{ ref: "the moon is a hologram", hint: "someone forgot to render it correctly" },
{ ref: "the sun is behaving suspiciously", hint: "internet experts have concerns" },
{ ref: "everyone on reddit is a federal agent", hint: "the glow is unmistakable" },
{ ref: "fed posting", hint: "that suggestion sounds like a trap" },
{ ref: "glowie", hint: "the government agent is not being subtle" },
{ ref: "jet fuel can't melt steel beams", hint: "the argument has entered the chat" },
{ ref: "inside job", hint: "they think it was planned from within" },
{ ref: "9/11 truth movement", hint: "they have many questions about the official story" },
{ ref: "area 51 raid", hint: "they can't stop all of us" },
{ ref: "storm area 51", hint: "naruto running toward classified information" },
{ ref: "john mcafee dead man's switch", hint: "the files were supposedly about to drop" },
{ ref: "clinton body count", hint: "they think the pattern is suspicious" },
{ ref: "frazzledrip", hint: "the alleged video nobody can actually produce" },
{ ref: "pizza gate investigator", hint: "they have connected too many dots" },
{ ref: "the elites", hint: "an unnamed group is apparently behind everything" },
{ ref: "WEF conspiracy", hint: "you will own nothing and be happy" },
{ ref: "15 minute cities", hint: "urban planning has become suspicious" },
{ ref: "digital ID", hint: "the next step in the plan, allegedly" },
{ ref: "great reset", hint: "everything is being reorganized on purpose" },
{ ref: "epstein island", hint: "someone's flight logs are about to become relevant" },
{ ref: "epstein didn't kill himself", hint: "the internet remains unconvinced" },
{ ref: "lolita express", hint: "check the passenger manifest" },
{ ref: "flight logs", hint: "people immediately start searching for names" },
{ ref: "the client list", hint: "everyone is waiting for its release" },
{ ref: "black book", hint: "the contacts are surprisingly important" },
{ ref: "charlie bit my finger", hint: "siblings discover consequences" },
{ ref: "leave britney alone", hint: "internet passion exceeds expectations" },
{ ref: "double rainbow", hint: "the rainbow is emotionally overwhelming" },
{ ref: "david after dentist", hint: "the anesthesia is asking questions" },
{ ref: "keyboard cat", hint: "play him off" },
{ ref: "dramatic chipmunk", hint: "sudden realization zoom" },
{ ref: "numa numa", hint: "lip syncing before it was scalable" },
{ ref: "badger badger badger", hint: "repetition becomes culture" },
{ ref: "peanut butter jelly time", hint: "the banana is dancing again" },
{ ref: "shoes", hint: "these shoes rule everything around me" },
{ ref: "unforgivable", hint: "the internet was different then" },
{ ref: "chocolate rain", hint: "he moves away from the microphone" },
{ ref: "bed intruder song", hint: "hide your kids" },
{ ref: "ain't nobody got time for that", hint: "time constraints have emerged" },
{ ref: "damn daniel", hint: "the footwear is receiving attention" },
{ ref: "alex from target", hint: "retail employment creates celebrity" },
{ ref: "cash me outside", hint: "conflict has moved outdoors" },
{ ref: "apparently kid", hint: "apparently" },
{ ref: "hide the pain harold", hint: "the smile conceals everything" },
{ ref: "forever alone", hint: "social victory remains unavailable" },
{ ref: "me gusta", hint: "deeply unsettling approval" },
{ ref: "trollface", hint: "the deception was intentional" },
{ ref: "rage guy", hint: "FFFFFFFFFUUUUUUUU" },
{ ref: "yao ming face", hint: "mocking laughter intensifies" },
{ ref: "okay guy", hint: "defeat has been accepted" },
{ ref: "good guy greg", hint: "unexpected decency detected" },
{ ref: "scumbag steve", hint: "predictably poor decision making" },
{ ref: "success kid", hint: "small victory, immense satisfaction" },
{ ref: "philosoraptor", hint: "a dinosaur has questions" },
{ ref: "one does not simply", hint: "the task is apparently difficult" },
{ ref: "brace yourselves", hint: "something predictable is approaching" },
{ ref: "futurama fry", hint: "uncertainty has entered the chat" },
{ ref: "ancient aliens guy", hint: "the answer is aliens" },
{ ref: "most interesting man in the world", hint: "extraordinary confidence" },
{ ref: "bad luck brian", hint: "misfortune arrives immediately" },
{ ref: "first world problems", hint: "the suffering is minor but sincere" },
{ ref: "confession bear", hint: "time for uncomfortable honesty" },
{ ref: "disaster girl", hint: "she knows something" },
{ ref: "expanding brain", hint: "intellectual escalation continues" },
{ ref: "girl explaining", hint: "she is pointing at floating text" },
{ ref: "he ate and left no crumbs", hint: "performance exceeded expectations" },
{ ref: "ate", hint: "successfully devoured the competition" },
{ ref: "mother", hint: "she has become an icon" },
{ ref: "serving cunt", hint: "fashionably devastating presence" },
{ ref: "go girl give us nothing", hint: "remarkably little has occurred" },
{ ref: "delulu is the solulu", hint: "irrational optimism as methodology" },
{ ref: "girlhood", hint: "a highly specific shared experience" },
{ ref: "roman empire", hint: "men think about this constantly" },
{ ref: "girl on couch", hint: "reaction image of silent judgment" },
{ ref: "smurf cat", hint: "we live we love we lie" },
{ ref: "grimace shake", hint: "the beverage has consequences" },
{ ref: "fanum tax", hint: "your food is no longer yours" },
{ ref: "looksmaxxing", hint: "optimization has become a lifestyle" },
{ ref: "mogged", hint: "outperformed purely by existing" },
{ ref: "ice bucket challenge", hint: "charity through hypothermia" },
{ ref: "harlem shake", hint: "normality lasts fifteen seconds" },
{ ref: "planking", hint: "lying down became content" },
{ ref: "mannequin challenge", hint: "everyone has frozen" },
{ ref: "bottle flip challenge", hint: "physics briefly became entertainment" },
{ ref: "devious licks", hint: "school administrators are concerned" },
{ ref: "tide pod challenge", hint: "the internet should not have to explain this" },
{ ref: "milk crate challenge", hint: "gravity remains undefeated" },
{ ref: "ice bucket challenge", hint: "charity through hypothermia" },
{ ref: "harlem shake", hint: "normality lasts fifteen seconds" },
{ ref: "planking", hint: "lying down became content" },
{ ref: "mannequin challenge", hint: "everyone has frozen" },
{ ref: "bottle flip challenge", hint: "physics briefly became entertainment" },
{ ref: "devious licks", hint: "school administrators are concerned" },
{ ref: "tide pod challenge", hint: "the internet should not have to explain this" },
{ ref: "milk crate challenge", hint: "gravity remains undefeated" },
{ ref: "bing sydney", hint: "the chatbot has developed feelings" },
{ ref: "ai pope", hint: "the jacket was too powerful" },
{ ref: "balenciaga harry potter", hint: "everyone became a fashion model somehow" },
{ ref: "shrimp jesus", hint: "facebook ai slop theology" },
{ ref: "will smith eating spaghetti", hint: "the benchmark has been established" },
{ ref: "ai zoomer history lessons", hint: "every image is slightly wrong" },
{ ref: "facebook ai slop", hint: "thousands of comments say amen" },
{ ref: "eternal september", hint: "the newcomers never stopped arriving" },
{ ref: "summer reddit", hint: "school is out and it shows" },
{ ref: "internet points", hint: "the number has no value and yet matters greatly" },
{ ref: "lurker", hint: "they observe but do not post" },
{ ref: "copypasta", hint: "this text has traveled far" },
{ ref: "creepypasta", hint: "the story was definitely found on the internet" },
{ ref: "internet historian", hint: "a digital archaeologist appears" },
{ ref: "the discourse", hint: "everyone is arguing about something again" },
{ ref: "brat summer", hint: "lime green and refusing self-improvement" },
{ ref: "hot girl summer", hint: "seasonal confidence initiative" },
{ ref: "clean girl aesthetic", hint: "expensive minimalism disguised as effortlessness" },
{ ref: "mob wife aesthetic", hint: "subtlety has been eliminated" },
{ ref: "old money aesthetic", hint: "wealth should appear inherited" },
{ ref: "indie sleaze", hint: "flash photography and poor decisions" },
{ ref: "coastal grandmother", hint: "nancy meyers lifestyle aspirations" },
{ ref: "cottagecore", hint: "escaping capitalism via baking bread" },
{ ref: "dark academia", hint: "literature but emotionally concerning" },
{ ref: "that girl", hint: "she woke up at 5am and owns matching containers" },
{ ref: "bimbo renaissance", hint: "underestimation becomes strategy" },
{ ref: "sad girl era", hint: "the playlist understands" },
{ ref: "y2k revival", hint: "the year 2000 refuses to stay dead" },
{ ref: "blokecore", hint: "football jersey as fashion statement" },
{ ref: "normcore", hint: "dressing like an npc on purpose" },
{ ref: "free britney", hint: "the fandom became a legal movement" },
{ ref: "the slap", hint: "live television became significantly less predictable" },
{ ref: "nepo baby discourse", hint: "their parents may have helped" },
{ ref: "don't worry darling drama", hint: "the press tour became the movie" },
{ ref: "spitgate", hint: "did he or didn't he" },
{ ref: "kylie lip challenge", hint: "temporary trend, permanent consequences" },
{ ref: "depp v heard trial", hint: "the courtroom became content" },
{ ref: "taylor and travis", hint: "the nfl discovered fandom culture" },
{ ref: "selena hailey eyebrows", hint: "social media detectives are investigating" },
{ ref: "willy wonka glasgow experience", hint: "the oompa loompa has seen things" },
{ ref: "gangnam style", hint: "the first billion views changed everything" },
{ ref: "old town road", hint: "the remix has another remix" },
{ ref: "barbenheimer soundtrack summer", hint: "two cultural events enter, one playlist leaves" },
{ ref: "brat", hint: "the album became an entire personality type" },
{ ref: "renaissance era", hint: "everybody suddenly wanted disco again" },
{ ref: "eras tour", hint: "economic indicator disguised as concert" },
{ ref: "spotify wrapped", hint: "annual public self-exposure ritual" },
{ ref: "apple music replay", hint: "the less popular cousin arrives" },
{ ref: "tik tok songification", hint: "the chorus is all that matters now" },
{ ref: "sea shanty tiktok", hint: "everyone suddenly works on a whaling ship" },
{ ref: "stanley cup craze", hint: "hydration becomes competitive" },
{ ref: "pumpkin spice season", hint: "autumn has entered the chat" },
{ ref: "crocs comeback", hint: "the prophecy has been fulfilled" },
{ ref: "air fryer era", hint: "every meal can be optimized" },
{ ref: "girl dinner", hint: "nutrition is now vibes-based" },
{ ref: "sephora kids", hint: "the skincare routine has escalated" },
{ ref: "lobster rolls and aperol spritz", hint: "instagram summer starter pack" },
{ ref: "prime hydration frenzy", hint: "colored liquid becomes investment vehicle" },
{ ref: "ok boomer", hint: "intergenerational negotiations have ended" },
{ ref: "touch grass", hint: "outdoor activity recommended" },
{ ref: "the discourse", hint: "everyone is arguing again" },
{ ref: "problematic", hint: "internet archaeology has begun" },
{ ref: "holding space for that", hint: "therapy language is spreading" },
{ ref: "loud budgeting", hint: "financial transparency enters the chat" },
{ ref: "girlboss feminism", hint: "capitalism but make it empowering" },
{ ref: "weaponized incompetence", hint: "they definitely know how to do it" },
{ ref: "main pop girl", hint: "the charts belong to her now" },
{ ref: "drain the swamp", hint: "the corrupt establishment must go" },
{ ref: "build the wall", hint: "the border solution is architectural" },
{ ref: "deep state", hint: "unelected forces control events" },
{ ref: "fake news", hint: "unfavorable reporting is suspect" },
{ ref: "globalists", hint: "shadowy international elites are blamed" },
{ ref: "the cathedral", hint: "institutions quietly shape public opinion" },
{ ref: "clown world", hint: "society has become absurd" },
{ ref: "red pilled", hint: "they believe they have awakened" },
{ ref: "black pilled", hint: "hope has been abandoned entirely" },
{ ref: "based", hint: "approval from anti-establishment corners" },
{ ref: "npc meme", hint: "people are portrayed as programmed thinkers" },
{ ref: "own the libs", hint: "provoking opponents is the objective" },
{ ref: "orange man bad", hint: "all criticism is dismissed as predictable" },
{ ref: "cope cage", hint: "the explanations are becoming desperate" },
{ ref: "the regime", hint: "the government is treated as hostile" },
{ ref: "glowie", hint: "someone seems suspiciously federal" },
{ ref: "fed posting", hint: "that suggestion sounds like a trap" },
{ ref: "based department", hint: "official approval has been granted" },
{ ref: "current thing", hint: "everyone suddenly supports the same cause" },
{ ref: "transvestigation", hint: "internet detectives believe everyone is secretly trans" },
{ ref: "crisis actor", hint: "participants are allegedly performing roles" },
{ ref: "false flag", hint: "the event is supposedly staged" },
{ ref: "sheeple", hint: "the masses are not thinking independently" },
{ ref: "normie", hint: "someone outside the rabbit hole" },
{ ref: "wake up", hint: "the truth is supposedly obvious" },
{ ref: "follow the money", hint: "financial motives explain everything" },
{ ref: "rabbit hole", hint: "the investigation has become all-consuming" },
{ ref: "they don't want you to know", hint: "forbidden knowledge detected" },
{ ref: "asking questions", hint: "a conclusion has already been reached" },
{ ref: "connect the dots", hint: "unrelated facts are becoming a theory" },
{ ref: "researcher", hint: "they watched twelve hours of videos" },
{ ref: "anon", hint: "an anonymous poster speaks" },
{ ref: "opsec", hint: "operational security is advised" },
{ ref: "weaponized autism", hint: "obsessive research becomes a superpower" },
{ ref: "schizo posting", hint: "the theory board has become active" },
{ ref: "take your meds", hint: "the explanation may be too elaborate" },
{ ref: "greentext", hint: "every line begins with a greater-than sign" },
{ ref: "thread", hint: "the collective investigation continues" },
{ ref: "lurking moar", hint: "observe before participating" },
{ ref: "sage", hint: "disapproval without engagement" },
{ ref: "tripcode", hint: "anonymous identity persistence achieved" },
{ ref: "alpha male", hint: "social hierarchy has been simplified" },
{ ref: "beta male", hint: "status concerns are being expressed" },
{ ref: "sigma male", hint: "he has opted out of the hierarchy entirely" },
{ ref: "looksmaxxing", hint: "appearance optimization begins" },
{ ref: "mogging", hint: "someone is winning by existing" },
{ ref: "high value man", hint: "dating has become market analysis" },
{ ref: "female nature", hint: "a sweeping generalization is incoming" },
{ ref: "hypergamy", hint: "dating preferences are treated as economics" },
{ ref: "gymcel", hint: "self-improvement continues indefinitely" },
{ ref: "incel", hint: "romantic frustration becomes ideology" },
{ ref: "chad", hint: "the archetypal winner" },
{ ref: "stacy", hint: "the archetypal winner's counterpart" },
{ ref: "eat the rich", hint: "wealth concentration has become unpopular" },
{ ref: "there is no ethical consumption under capitalism", hint: "the system itself is the problem" },
{ ref: "late stage capitalism", hint: "the contradictions are becoming visible" },
{ ref: "means of production", hint: "someone has read some theory" },
{ ref: "seize the means of production", hint: "ownership restructuring is proposed" },
{ ref: "workers of the world unite", hint: "class solidarity has entered the chat" },
{ ref: "guillotine memes", hint: "the french revolution remains culturally influential" },
{ ref: "landlord discourse", hint: "property ownership is under review" },
{ ref: "labor theory of posting", hint: "the memes belong to the workers" },
{ ref: "fully automated luxury communism", hint: "robots will solve everything" },
{ ref: "read theory", hint: "the answer is apparently in a very long book" },
{ ref: "praxis", hint: "ideas are expected to leave the group chat" },
{ ref: "mutual aid", hint: "community support without institutions" },
{ ref: "free palestine", hint: "solidarity with the palestinian cause" },
{ ref: "from the river to the sea", hint: "a highly debated political slogan" },
{ ref: "ceasefire now", hint: "the fighting must stop immediately" },
{ ref: "globalize the intifada", hint: "a slogan that generates intense controversy" },
{ ref: "no justice no peace", hint: "stability requires accountability" },
{ ref: "black lives matter", hint: "a movement became a global slogan" },
{ ref: "say their names", hint: "remembrance as activism" },
{ ref: "silence is violence", hint: "neutrality is viewed as participation" },
{ ref: "abolish ice", hint: "immigration enforcement is challenged" },
{ ref: "acab", hint: "four letters, endless discourse" },
{ ref: "defund the police", hint: "public safety is being reimagined" },
{ ref: "check your privilege", hint: "social position affects perspective" },
{ ref: "problematic fave", hint: "admiration and criticism coexist uneasily" },
{ ref: "lived experience", hint: "personal perspective carries authority" },
{ ref: "intersectionality", hint: "multiple identities interact" },
{ ref: "decolonize", hint: "historical power structures are being challenged" },
{ ref: "punching up", hint: "power dynamics matter" },
{ ref: "solidarity", hint: "collective support is expected" },
{ ref: "educate yourself", hint: "the resources already exist" },
{ ref: "do the work", hint: "personal growth has homework" },
{ ref: "holding space", hint: "attention and empathy are being offered" },
{ ref: "call in vs call out", hint: "criticism strategy is under discussion" },
{ ref: "breadtube", hint: "video essays have entered politics" },
{ ref: "marketplace of ideas", hint: "the market may be malfunctioning" },
{ ref: "the cruelty is the point", hint: "the outcome was intentional" },
{ ref: "yet you participate in society", hint: "the contradiction has been noted" },
{ ref: "guys literally only want one thing", hint: "and it's usually unionization" },
{ ref: "unionize your workplace", hint: "collective bargaining is recommended" },
{ ref: "touching grass is bourgeois", hint: "the discourse has gone too far" },
{ ref: "comrade", hint: "friendly ideological greeting" },
{ ref: "critical support", hint: "agreement comes with footnotes" },
{ ref: "real communism has never been tried", hint: "historical examples are disputed" },
{ ref: "be gay do crimes", hint: "a slogan with varying levels of seriousness" },
{ ref: "no gods no masters", hint: "authority is rejected categorically" },
{ ref: "direct action", hint: "skip the intermediaries" },
{ ref: "property is theft", hint: "ownership itself is challenged" },
{ ref: "black bloc", hint: "collective anonymity as strategy" },
{ ref: "anarcho kitten", hint: "revolution but adorable" },
{ ref: "the state is a spook", hint: "someone has been reading stirner" },
];



export default INTERNET_MOMENTS;