const INTERNET_MOMENTS = [
  { ref: "man vs bear viral tiktok", hint: "she chose the bear" },
  { ref: "the dress — blue/black or white/gold", hint: "nobody agrees on what they saw" },
  { ref: "salt bae", hint: "someone sprinkles something with unnecessary precision" },
  { ref: "we did it reddit", hint: "the crowd takes credit for something they didn't do" },
  { ref: "girl dinner", hint: "this is her meal. it is not enough. it is everything." },
  { ref: "NPC livestreamer", hint: "she moves like she is running a loop" },
  { ref: "very demure very mindful", hint: "she is being very demure about this" },
  { ref: "brain rot", hint: "something here has fully rotted" },
  { ref: "understood the assignment", hint: "she understood the assignment" },
  { ref: "we are so back / it is so over", hint: "pick one. make it count." },
  { ref: "main character syndrome", hint: "everyone else is just an NPC" },
{ ref: "this is fine dog", hint: "everything is visibly on fire" },
{ ref: "distracted boyfriend", hint: "he has noticed something else" },
{ ref: "woman yelling at cat", hint: "one side is emotional, the other is eating salad" },
{ ref: "gigachad", hint: "the impossibly correct specimen" },
{ ref: "sigma male", hint: "he has rejected society and purchased a podcast microphone" },
{ ref: "skibidi toilet", hint: "nobody can explain why this became civilization" },
{ ref: "ohio meme", hint: "only in ohio" },
{ ref: "rizz", hint: "he possesses inexplicable charisma" },
{ ref: "the backrooms", hint: "you have clipped out of reality" },
{ ref: "liminal spaces", hint: "this place feels wrong for some reason" },
{ ref: "analog horror", hint: "the VHS tape knows something" },
{ ref: "NPC meme", hint: "their dialogue tree has ended" },
{ ref: "touch grass", hint: "please go outside immediately" },
{ ref: "chronically online", hint: "they have seen too much internet" },
{ ref: "ratio", hint: "the replies have spoken" },
{ ref: "cope", hint: "that explanation sounds self-soothing" },
{ ref: "seethe", hint: "they are not taking this well" },
{ ref: "based", hint: "unexpectedly respectable" },
{ ref: "cringe", hint: "secondhand embarrassment detected" },
{ ref: "mid", hint: "it exists. that is all." },
{ ref: "let him cook", hint: "the vision is not yet complete" },
{ ref: "cooked", hint: "the situation cannot be salvaged" },
{ ref: "delulu", hint: "delusion has become strategy" },
{ ref: "girl math", hint: "the arithmetic is emotionally correct" },
{ ref: "boy math", hint: "the arithmetic is emotionally incorrect" },
{ ref: "girlboss", hint: "she is succeeding, perhaps too hard" },
{ ref: "gatekeep gaslight girlboss", hint: "the holy trinity" },
{ ref: "beige flag", hint: "a strangely specific personality trait" },
{ ref: "red flag", hint: "abandon ship" },
{ ref: "green flag", hint: "unexpectedly healthy behavior" },
{ ref: "ick", hint: "attraction has been instantly deleted" },
{ ref: "situationship", hint: "nobody involved can define the relationship" },
{ ref: "soft launching", hint: "someone is hiding a partner in frame" },
{ ref: "hard launching", hint: "the relationship is now public information" },
{ ref: "quiet quitting", hint: "doing exactly what the job requires" },
{ ref: "lying flat", hint: "opting out of the hustle" },
{ ref: "antiwork", hint: "the spreadsheet can wait" },
{ ref: "rent free", hint: "it occupies too much mental space" },
{ ref: "doomscrolling", hint: "one more terrible post" },
{ ref: "doomposting", hint: "the future has been cancelled" },
{ ref: "weird twitter", hint: "the joke has escaped conventional structure" },
{ ref: "shitposting", hint: "quality was never the objective" },
{ ref: "posting through it", hint: "the emotional crisis continues online" },
{ ref: "many such cases", hint: "apparently this keeps happening" },
{ ref: "source: i made it up", hint: "citation unavailable" },
{ ref: "bro visited his friend", hint: "something catastrophic has happened" },
{ ref: "nah id win", hint: "confidence exceeding available evidence" },
{ ref: "stand proud", hint: "you were strong" },
{ ref: "is he stupid?", hint: "the internet's preferred question" },
{ ref: "they don't know", hint: "the secret remains mine alone" },
{ ref: "nobody: absolutely nobody:", hint: "someone did something unprompted" },
{ ref: "how do you do fellow kids", hint: "an institution attempts relevance" },
{ ref: "cheems", hint: "speech impediment dog wisdom" },
{ ref: "doge", hint: "such internet. very meme." },
{ ref: "stonks", hint: "financial expertise not required" },
{ ref: "diamond hands", hint: "selling is not an option" },
{ ref: "to the moon", hint: "investment strategy powered by optimism" },
{ ref: "ape together strong", hint: "collective irrationality" },
{ ref: "goblin mode", hint: "personal standards have been suspended" },
{ ref: "feral", hint: "civilization is losing its grip" },
{ ref: "no thoughts head empty", hint: "the brain is offline" },
{ ref: "he just like me fr", hint: "uncomfortable personal identification" },
{ ref: "the masculine urge", hint: "an extremely specific impulse" },
{ ref: "the feminine urge", hint: "an equally specific impulse" },
{ ref: "corecore", hint: "an emotional montage of the human condition" },
{ ref: "cottagecore", hint: "internet yearning for rural fantasy" },
{ ref: "goblincore", hint: "crow brain aesthetics" },
{ ref: "AI generated hands", hint: "something is wrong with the fingers" },
{ ref: "prompt engineer", hint: "typing has become a profession" },
{ ref: "chatgpt wrote this", hint: "suspiciously polished prose" },
{ ref: "dead internet theory", hint: "what if everyone here is a bot" },
{ ref: "reply guy", hint: "he appears beneath every post" },
{ ref: "cancelled", hint: "today's public execution" },
{ ref: "receipts", hint: "the screenshots have arrived" },
{ ref: "subtweet", hint: "a targeted message without naming names" },
{ ref: "parasocial relationship", hint: "they feel like close friends who have never met" },
{ ref: "babe wake up", hint: "a new development has dropped" },
{ ref: "the algorithm", hint: "an invisible force controls all outcomes" },
{ ref: "for you page", hint: "the machine knows your interests" },
{ ref: "i'm looking for the guy", hint: "an impossible search begins" },
{ ref: "absolute cinema", hint: "peak culture has been achieved" },
{ ref: "go piss girl", hint: "a strange form of encouragement" },
{ ref: "woman in STEM", hint: "she is engineering a terrible decision" },
{ ref: "unhinged", hint: "restraints have been removed" },
{ ref: "canon event", hint: "this suffering is mandatory" },
{ ref: "he's literally me", hint: "dangerous levels of identification" },
{ ref: "POV", hint: "that is not how POV works anymore" },
{ ref: "normalize this", hint: "social consensus is being requested" },
{ ref: "you won the internet today", hint: "temporary online supremacy achieved" },
{ ref: "the internet remains undefeated", hint: "collective creativity has become dangerous" },
{ ref: "birds aren't real", hint: "the pigeons are government surveillance devices" },
{ ref: "dead internet theory", hint: "most of the internet is bots talking to bots" },
{ ref: "gang stalking", hint: "they believe strangers are coordinating against them" },
{ ref: "mk ultra", hint: "the CIA definitely did something weird here" },
{ ref: "project blue beam", hint: "the fake alien invasion is coming any day now" },
{ ref: "chemtrails", hint: "those airplane lines are supposedly not just clouds" },
{ ref: "lizard people", hint: "the world's leaders may be reptiles" },
{ ref: "new world order", hint: "a secret global elite controls everything" },
{ ref: "illuminati", hint: "the triangle appears again" },
{ ref: "bohemian grove", hint: "powerful people meet in the woods for mysterious reasons" },
{ ref: "bilderberg group", hint: "another meeting nobody is supposed to understand" },
{ ref: "reptilian shapeshifters", hint: "their eyes glitched for a frame" },
{ ref: "moon landing hoax", hint: "they think it was filmed on a soundstage" },
{ ref: "flat earth", hint: "the horizon has become a personality trait" },
{ ref: "hollow earth", hint: "there is apparently another world underneath us" },
{ ref: "antarctica conspiracy", hint: "something important is hidden beyond the ice" },
{ ref: "simulation theory", hint: "reality may be running on somebody else's hardware" },
{ ref: "mandela effect", hint: "everyone remembers it differently" },
{ ref: "berenstain bears", hint: "the spelling has allegedly changed timelines" },
{ ref: "cern opened a portal", hint: "physics has gone too far" },
{ ref: "quantum immortality", hint: "you never experience your own death" },
{ ref: "targeted individual", hint: "they believe the universe is watching them specifically" },
{ ref: "crisis actor", hint: "every event is supposedly staged" },
{ ref: "false flag operation", hint: "nothing is ever what it appears to be" },
{ ref: "pizzagate", hint: "the basement that didn't exist" },
{ ref: "qanon", hint: "the clues are hidden in cryptic posts" },
{ ref: "the storm is coming", hint: "the promised reckoning never arrives" },
{ ref: "adrenochrome", hint: "internet mythology disguised as research" },
{ ref: "wayfair conspiracy", hint: "the furniture is suspiciously expensive" },
{ ref: "5g mind control", hint: "the cell tower is apparently responsible" },
{ ref: "vaccines contain microchips", hint: "the tracking device is somehow microscopic" },
{ ref: "black helicopters", hint: "unmarked aircraft mean something ominous" },
{ ref: "number stations", hint: "the radio keeps reading random numbers" },
{ ref: "HAARP", hint: "the weather is being controlled remotely" },
{ ref: "Denver airport conspiracy", hint: "the murals know too much" },
{ ref: "area 51", hint: "the aliens are probably in there" },
{ ref: "men in black", hint: "someone wants witnesses to stop talking" },
{ ref: "roswell incident", hint: "the weather balloon explanation remains controversial" },
{ ref: "ufo cover-up", hint: "the government has known all along" },
{ ref: "ancient aliens", hint: "humans definitely couldn't have built that" },
{ ref: "lost civilization of atlantis", hint: "there was supposedly an advanced society before history" },
{ ref: "giants existed", hint: "the skeleton photo was removed from the internet" },
{ ref: "mud flood theory", hint: "an entire civilization was buried recently" },
{ ref: "tartaria", hint: "the missing empire behind every old building" },
{ ref: "black knight satellite", hint: "something ancient is orbiting earth" },
{ ref: "face on mars", hint: "the blurry photo changes everything" },
{ ref: "paul is dead", hint: "the beatle was secretly replaced" },
{ ref: "elvis is alive", hint: "someone saw him at a grocery store" },
{ ref: "tu pac is alive", hint: "he is reportedly living somewhere unexpected" },
{ ref: "avril lavigne replacement theory", hint: "they think the original singer disappeared" },
{ ref: "clone theory", hint: "that celebrity has been replaced" },
{ ref: "celebrity humiliation ritual", hint: "the performance was supposedly symbolic" },
{ ref: "predictive programming", hint: "movies are secretly telling the future" },
{ ref: "the matrix glitch", hint: "reality briefly revealed the seams" },
{ ref: "npc theory", hint: "some people are allegedly background characters" },
{ ref: "backrooms found footage", hint: "someone accidentally escaped reality" },
{ ref: "slenderman sightings", hint: "the tall figure keeps appearing in photos" },
{ ref: "cicada 3301", hint: "an impossibly elaborate puzzle is recruiting people" },
{ ref: "polybius", hint: "the arcade machine nobody can prove existed" },
{ ref: "lake city quiet pills", hint: "a reddit mystery nobody fully solved" },
{ ref: "maxwellhill account theory", hint: "an old reddit account became unexpectedly interesting" },
{ ref: "celebrities are secretly immortal", hint: "they have looked the same for decades" },
{ ref: "time traveler john titor", hint: "a forum poster claimed to be from the future" },
{ ref: "finland does not exist", hint: "the country is allegedly a fishing conspiracy" },
{ ref: "wyoming does not exist", hint: "have you actually met anyone from there" },
{ ref: "birds work for the bourgeoisie", hint: "the joke conspiracy has evolved" },
{ ref: "the moon is a hologram", hint: "someone forgot to render it correctly" },
{ ref: "the sun is behaving suspiciously", hint: "internet experts have concerns" },
{ ref: "everyone on reddit is a federal agent", hint: "the glow is unmistakable" },
{ ref: "fed posting", hint: "that suggestion sounds like a trap" },
{ ref: "glowie", hint: "the government agent is not being subtle" },
{ ref: "jet fuel can't melt steel beams", hint: "the argument has entered the chat" },
{ ref: "inside job", hint: "they think it was planned from within" },
{ ref: "9/11 truth movement", hint: "they have many questions about the official story" },
{ ref: "area 51 raid", hint: "they can't stop all of us" },
{ ref: "storm area 51", hint: "naruto running toward classified information" },
{ ref: "john mcafee dead man's switch", hint: "the files were supposedly about to drop" },
{ ref: "clinton body count", hint: "they think the pattern is suspicious" },
{ ref: "frazzledrip", hint: "the alleged video nobody can actually produce" },
{ ref: "pizza gate investigator", hint: "they have connected too many dots" },
{ ref: "the elites", hint: "an unnamed group is apparently behind everything" },
{ ref: "WEF conspiracy", hint: "you will own nothing and be happy" },
{ ref: "15 minute cities", hint: "urban planning has become suspicious" },
{ ref: "digital ID", hint: "the next step in the plan, allegedly" },
{ ref: "great reset", hint: "everything is being reorganized on purpose" },
{ ref: "epstein island", hint: "someone's flight logs are about to become relevant" },
{ ref: "epstein didn't kill himself", hint: "the internet remains unconvinced" },
{ ref: "lolita express", hint: "check the passenger manifest" },
{ ref: "flight logs", hint: "people immediately start searching for names" },
{ ref: "the client list", hint: "everyone is waiting for its release" },
{ ref: "black book", hint: "the contacts are surprisingly important" },
];



export default INTERNET_MOMENTS;