[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && npx prisma generate && npx prisma db push"

[deploy]
startCommand = "cd backend && node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3