"""
Living Story sidecar -- subject cutout only
===========================================

Responsibilities (everything else moved to the backend):
  - Download the original image from Cloudinary
  - Run rembg background removal (isnet-general-use)
  - Hard-threshold the alpha for a clean, fringe-free edge
  - Upload the subject cutout PNG to Cloudinary
  - Accept pre-masked face crop blobs from the frontend (MediaPipe),
    upload them straight to Cloudinary -- no cv2, no face detection

Description (LLaVA) is now generated in the backend via llm.service.js.

Fixes vs previous version
--------------------------
* Removed all Unicode arrow/special characters from print() calls --
  Python 3.13 on Windows defaults to cp1252 which cannot encode them.
  All log strings now use only plain ASCII.
* Removed cv2, face detection, LLaVA, base64 -- not needed here anymore.
"""

import os
import io
import numpy as np
import requests
from flask import Flask, request, jsonify
from PIL import Image
from rembg import remove, new_session
import cloudinary
import cloudinary.uploader
from dotenv import load_dotenv
from waitress import serve

load_dotenv()

cloudinary.config(
    cloud_name=os.environ["CLOUDINARY_CLOUD_NAME"],
    api_key=os.environ["CLOUDINARY_API_KEY"],
    api_secret=os.environ["CLOUDINARY_API_SECRET"],
)

app = Flask(__name__)

print("Loading rembg model (isnet-general-use)...")
REMBG_SESSION = new_session("isnet-general-use")
print("rembg model ready.")

# Alpha pixels below this value snap to fully transparent.
# 128 keeps confident foreground, drops the soft halo rembg produces.
ALPHA_THRESHOLD =25


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def hard_alpha(img: Image.Image, threshold: int = ALPHA_THRESHOLD) -> Image.Image:
    """Snap rembg's soft alpha to a hard 0/255 edge."""
    img = img.convert("RGBA")
    r, g, b, a = img.split()
    a_np = np.array(a)
    a_np = np.where(a_np >= threshold, 255, 0).astype(np.uint8)
    img.putalpha(Image.fromarray(a_np, mode="L"))
    return img


def upload_pil(img: Image.Image, public_id: str, context: dict) -> str:
    """Upload a PIL RGBA image to Cloudinary and return its secure URL."""
    ctx_str = "|".join(f"{k}={v}" for k, v in context.items())
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    result = cloudinary.uploader.upload(
        buf,
        folder="living-story/cutouts",
        public_id=public_id,
        resource_type="image",
        context=ctx_str,
    )
    return result["secure_url"]


# ---------------------------------------------------------------------------
# Route
# ---------------------------------------------------------------------------

@app.route("/cutout", methods=["POST"])
def cutout():
    """
    Accepts multipart/form-data:
      image_url    -- Cloudinary URL of the original photo (required)
      day          -- story day string (optional)
      uploaderName -- uploader display name (optional)
      left_eye     -- pre-masked PNG blob from MediaPipe (optional)
      right_eye    -- pre-masked PNG blob from MediaPipe (optional)
      mouth        -- pre-masked PNG blob from MediaPipe (optional)

    Returns JSON: { subject, left_eye?, right_eye?, mouth? }

    Description is NOT returned. It is generated by the backend
    (describeImage in llm.service.js) which has direct Ollama access.
    """
    print("[SIDECAR] /cutout request received")

    if request.content_type and "multipart" in request.content_type:
        image_url      = request.form.get("image_url", "")
        day            = request.form.get("day", "")
        uploader_name  = request.form.get("uploaderName", "")
        left_eye_file  = request.files.get("left_eye")
        right_eye_file = request.files.get("right_eye")
        mouth_file     = request.files.get("mouth")
    else:
        # Fallback: plain JSON (e.g. direct service call / tests)
        data           = request.get_json() or {}
        image_url      = data.get("image_url", "")
        day            = data.get("day", "")
        uploader_name  = data.get("uploaderName", "")
        left_eye_file  = None
        right_eye_file = None
        mouth_file     = None

    if not image_url:
        return jsonify({"error": "image_url required"}), 400

    print("[SIDECAR] Downloading image from Cloudinary...")
    resp = requests.get(image_url, timeout=15)
    img  = Image.open(io.BytesIO(resp.content)).convert("RGB")
    print(f"[SIDECAR] Downloaded: {img.size[0]}x{img.size[1]}px")
    uid  = str(abs(hash(image_url)))[-8:]

    base_ctx = {"day": str(day), "uploader": uploader_name}
    results  = {}

    # -- Subject cutout -------------------------------------------------------
    print("[REMBG] Removing background...")
    raw     = remove(img, session=REMBG_SESSION)
    subject = hard_alpha(raw)
    print("[REMBG] Done. Uploading subject cutout...")
    results["subject"] = upload_pil(
        subject,
        f"{uid}_subject",
        {**base_ctx, "cutout_type": "subject"},
    )
    print(f"[CLOUDINARY] Subject uploaded: {results['subject']}")

    # -- Face crops from frontend (MediaPipe) ---------------------------------
    face_files = {
        "left_eye":  left_eye_file,
        "right_eye": right_eye_file,
        "mouth":     mouth_file,
    }

    has_face_crops = any(f is not None for f in face_files.values())
    if has_face_crops:
        print("[FACE] Uploading frontend-provided face crops:")
        for key, fobj in face_files.items():
            if fobj is None:
                continue
            print(f"[FACE]   uploading {key}...")
            crop_img = Image.open(fobj.stream).convert("RGBA")
            results[key] = upload_pil(
                crop_img,
                f"{uid}_{key}",
                {**base_ctx, "cutout_type": key},
            )
            print(f"[CLOUDINARY] {key} uploaded: {results[key]}")
    else:
        print("[FACE] No face crops received -- subject cutout only.")

    print(f"[SIDECAR] Done. Keys returned: {list(results.keys())}")
    return jsonify(results)


@app.route("/health")
def health():
    return jsonify({"status": "ok"})


if __name__ == "__main__":
    print("Starting Living Story sidecar on port 5001...")
    serve(app, host="0.0.0.0", port=5001)